/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AuthenticateAuthenticateV2ResponseMPayload } from './authenticateAuthenticateV2ResponseMPayload';

export class AuthenticateAuthenticateV2ResponseAllOf {
    'mPayload': AuthenticateAuthenticateV2ResponseMPayload;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mPayload",
            "baseName": "mPayload",
            "type": "AuthenticateAuthenticateV2ResponseMPayload"
        }    ];

    static getAttributeTypeMap() {
        return AuthenticateAuthenticateV2ResponseAllOf.attributeTypeMap;
    }
}

