/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.46
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Request for the /2/module/authenticate/authenticate API Request
*/
export class AuthenticateAuthenticateV2Request {
    /**
    * The customer code assigned to your account
    */
    'pksCustomerCode': string;
    /**
    * The email address.
    */
    'sEmailAddress'?: string;
    /**
    * The Login name of the User.
    */
    'sUserLoginname'?: string;
    /**
    * A Password.  Must meet complexity requirements
    */
    'sPassword'?: string;
    /**
    * A Password encrypted and encoded in Base64  Must meet complexity requirements
    */
    'sPasswordEncrypted'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pksCustomerCode",
            "baseName": "pksCustomerCode",
            "type": "string"
        },
        {
            "name": "sEmailAddress",
            "baseName": "sEmailAddress",
            "type": "string"
        },
        {
            "name": "sUserLoginname",
            "baseName": "sUserLoginname",
            "type": "string"
        },
        {
            "name": "sPassword",
            "baseName": "sPassword",
            "type": "string"
        },
        {
            "name": "sPasswordEncrypted",
            "baseName": "sPasswordEncrypted",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AuthenticateAuthenticateV2Request.attributeTypeMap;
    }
}

