/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Payload for the /2/module/authenticate/authenticate API Request
*/
export class AuthenticateAuthenticateV2ResponseMPayload {
    /**
    * The Authorization key
    */
    'sAuthorization': string;
    /**
    * The secret key
    */
    'sSecret': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sAuthorization",
            "baseName": "sAuthorization",
            "type": "string"
        },
        {
            "name": "sSecret",
            "baseName": "sSecret",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AuthenticateAuthenticateV2ResponseMPayload.attributeTypeMap;
    }
}

