/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.31
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Gives informations about the user that created the object and the last user to have modified it.  If the object was never modified after creation, both Created and Modified informations will be the same.  Apikey details will only be provided if the changes were made by an API key.  
*/
export class CommonAudit {
    /**
    * The id of the User that created the object.
    */
    'fkiUserIDCreated': number;
    /**
    * The id of the User that made the last modification on the object.
    */
    'fkiUserIDModified': number;
    /**
    * The id of the API Key that created the object.
    */
    'fkiApikeyIDCreated'?: number;
    /**
    * The id of the API Key that made the last modification on the object.
    */
    'fkiApikeyIDModified'?: number;
    /**
    * Represent a Date Time. The timezone is the one configured in the User\'s profile.
    */
    'dtCreatedDate': string;
    /**
    * Represent a Date Time. The timezone is the one configured in the User\'s profile.
    */
    'dtModifiedDate': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fkiUserIDCreated",
            "baseName": "fkiUserIDCreated",
            "type": "number"
        },
        {
            "name": "fkiUserIDModified",
            "baseName": "fkiUserIDModified",
            "type": "number"
        },
        {
            "name": "fkiApikeyIDCreated",
            "baseName": "fkiApikeyIDCreated",
            "type": "number"
        },
        {
            "name": "fkiApikeyIDModified",
            "baseName": "fkiApikeyIDModified",
            "type": "number"
        },
        {
            "name": "dtCreatedDate",
            "baseName": "dtCreatedDate",
            "type": "string"
        },
        {
            "name": "dtModifiedDate",
            "baseName": "dtModifiedDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CommonAudit.attributeTypeMap;
    }
}

