/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Generic Error Message
*/
export class CommonResponseError {
    /**
    * More detail about the error
    */
    'sErrorMessage': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sErrorMessage",
            "baseName": "sErrorMessage",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CommonResponseError.attributeTypeMap;
    }
}

