/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContactRequest } from './contactRequest';
import { ContactRequestCompoundAllOf } from './contactRequestCompoundAllOf';
import { ContactinformationsRequestCompound } from './contactinformationsRequestCompound';

/**
* A Contact Object and children to create a complete structure
*/
export class ContactRequestCompound {
    'objContactinformations': ContactinformationsRequestCompound;
    /**
    * The unique ID of the Contacttitle.  Valid values:  |Value|Description| |-|-| |1|Ms.| |2|Mr.| |4|(Blank)| |5|Me (For Notaries)|
    */
    'fkiContacttitleID': number;
    /**
    * The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English|
    */
    'fkiLanguageID': number;
    /**
    * The First name of the contact
    */
    'sContactFirstname': string;
    /**
    * The Last name of the contact
    */
    'sContactLastname': string;
    /**
    * The Company name of the contact
    */
    'sContactCompany': string;
    /**
    * The Birth Date of the contact
    */
    'dtContactBirthdate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objContactinformations",
            "baseName": "objContactinformations",
            "type": "ContactinformationsRequestCompound"
        },
        {
            "name": "fkiContacttitleID",
            "baseName": "fkiContacttitleID",
            "type": "number"
        },
        {
            "name": "fkiLanguageID",
            "baseName": "fkiLanguageID",
            "type": "number"
        },
        {
            "name": "sContactFirstname",
            "baseName": "sContactFirstname",
            "type": "string"
        },
        {
            "name": "sContactLastname",
            "baseName": "sContactLastname",
            "type": "string"
        },
        {
            "name": "sContactCompany",
            "baseName": "sContactCompany",
            "type": "string"
        },
        {
            "name": "dtContactBirthdate",
            "baseName": "dtContactBirthdate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ContactRequestCompound.attributeTypeMap;
    }
}

