/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddressRequest } from './addressRequest';
import { EmailRequest } from './emailRequest';
import { PhoneRequest } from './phoneRequest';
import { WebsiteRequest } from './websiteRequest';

export class ContactinformationsRequestCompoundAllOf {
    'a_objAddress': Array<AddressRequest>;
    'a_objPhone': Array<PhoneRequest>;
    'a_objEmail': Array<EmailRequest>;
    'a_objWebsite': Array<WebsiteRequest>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "a_objAddress",
            "baseName": "a_objAddress",
            "type": "Array<AddressRequest>"
        },
        {
            "name": "a_objPhone",
            "baseName": "a_objPhone",
            "type": "Array<PhoneRequest>"
        },
        {
            "name": "a_objEmail",
            "baseName": "a_objEmail",
            "type": "Array<EmailRequest>"
        },
        {
            "name": "a_objWebsite",
            "baseName": "a_objWebsite",
            "type": "Array<WebsiteRequest>"
        }    ];

    static getAttributeTypeMap() {
        return ContactinformationsRequestCompoundAllOf.attributeTypeMap;
    }
}

