/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.31
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsigndocumentRequest } from './ezsigndocumentRequest';
import { EzsigndocumentRequestCompound } from './ezsigndocumentRequestCompound';

/**
* Request for the /1/object/ezsigndocument/createObject API Request
*/
export class EzsigndocumentCreateObjectV1Request {
    'objEzsigndocument'?: EzsigndocumentRequest;
    'objEzsigndocumentCompound'?: EzsigndocumentRequestCompound;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objEzsigndocument",
            "baseName": "objEzsigndocument",
            "type": "EzsigndocumentRequest"
        },
        {
            "name": "objEzsigndocumentCompound",
            "baseName": "objEzsigndocumentCompound",
            "type": "EzsigndocumentRequestCompound"
        }    ];

    static getAttributeTypeMap() {
        return EzsigndocumentCreateObjectV1Request.attributeTypeMap;
    }
}

