/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsigndocumentGetDownloadUrlV1ResponseMPayload } from './ezsigndocumentGetDownloadUrlV1ResponseMPayload';

export class EzsigndocumentGetDownloadUrlV1ResponseAllOf {
    'mPayload': EzsigndocumentGetDownloadUrlV1ResponseMPayload;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mPayload",
            "baseName": "mPayload",
            "type": "EzsigndocumentGetDownloadUrlV1ResponseMPayload"
        }    ];

    static getAttributeTypeMap() {
        return EzsigndocumentGetDownloadUrlV1ResponseAllOf.attributeTypeMap;
    }
}

