/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsignfolderRequest } from './ezsignfolderRequest';
import { EzsignfolderRequestCompound } from './ezsignfolderRequestCompound';

/**
* Request for the /1/object/ezsignfolder/createObject API Request
*/
export class EzsignfolderCreateObjectV1Request {
    'objEzsignfolder'?: EzsignfolderRequest;
    'objEzsignfolderCompound'?: EzsignfolderRequestCompound;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objEzsignfolder",
            "baseName": "objEzsignfolder",
            "type": "EzsignfolderRequest"
        },
        {
            "name": "objEzsignfolderCompound",
            "baseName": "objEzsignfolderCompound",
            "type": "EzsignfolderRequestCompound"
        }    ];

    static getAttributeTypeMap() {
        return EzsignfolderCreateObjectV1Request.attributeTypeMap;
    }
}

