/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Request for the /1/object/ezsigndocument/{pkiEzsigndocumentID}/getWordsPositions API Request
*/
export class EzsigndocumentGetWordsPositionsV1Request {
    'a_sWords': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "a_sWords",
            "baseName": "a_sWords",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return EzsigndocumentGetWordsPositionsV1Request.attributeTypeMap;
    }
}

