/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EzsignsignatureGetObjectV1ResponseAllOf {
    /**
    * Payload for the /1/object/ezsignsignature/getObject API Request
    */
    'mPayload': object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mPayload",
            "baseName": "mPayload",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return EzsignsignatureGetObjectV1ResponseAllOf.attributeTypeMap;
    }
}

