/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsignpageResponse } from './ezsignpageResponse';

/**
* Payload for the /1/object/ezsigndocument/{pkiEzsigndocument}/getEzsignpages API Request
*/
export class EzsigndocumentGetEzsignpagesV1ResponseMPayload {
    'a_objEzsignpage': Array<EzsignpageResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "a_objEzsignpage",
            "baseName": "a_objEzsignpage",
            "type": "Array<EzsignpageResponse>"
        }    ];

    static getAttributeTypeMap() {
        return EzsigndocumentGetEzsignpagesV1ResponseMPayload.attributeTypeMap;
    }
}

