/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsigndocumentRequest } from './ezsigndocumentRequest';

/**
* An Ezsigndocument Object and children to create a complete structure
*/
export class EzsigndocumentRequestCompound {
    /**
    * Indicates where to look for the document binary content.
    */
    'eEzsigndocumentSource': EzsigndocumentRequestCompound.EEzsigndocumentSourceEnum;
    /**
    * Indicates the format of the document.
    */
    'eEzsigndocumentFormat': EzsigndocumentRequestCompound.EEzsigndocumentFormatEnum;
    /**
    * The Base64 encoded binary content of the document.  This field is Required when eEzsigndocumentSource = Base64.
    */
    'sEzsigndocumentBase64'?: string;
    /**
    * A reference to a valid Ezsignfolder.  That value is returned after a successful Ezsignfolder Creation.
    */
    'fkiEzsignfolderID': number;
    /**
    * Represent a Date Time. The timezone is the one configured in the User\'s profile.
    */
    'dtEzsigndocumentDuedate': string;
    /**
    * The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English|
    */
    'fkiLanguageID': number;
    /**
    * The name of the document that will be presented to Ezsignfoldersignerassociations
    */
    'sEzsigndocumentName': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eEzsigndocumentSource",
            "baseName": "eEzsigndocumentSource",
            "type": "EzsigndocumentRequestCompound.EEzsigndocumentSourceEnum"
        },
        {
            "name": "eEzsigndocumentFormat",
            "baseName": "eEzsigndocumentFormat",
            "type": "EzsigndocumentRequestCompound.EEzsigndocumentFormatEnum"
        },
        {
            "name": "sEzsigndocumentBase64",
            "baseName": "sEzsigndocumentBase64",
            "type": "string"
        },
        {
            "name": "fkiEzsignfolderID",
            "baseName": "fkiEzsignfolderID",
            "type": "number"
        },
        {
            "name": "dtEzsigndocumentDuedate",
            "baseName": "dtEzsigndocumentDuedate",
            "type": "string"
        },
        {
            "name": "fkiLanguageID",
            "baseName": "fkiLanguageID",
            "type": "number"
        },
        {
            "name": "sEzsigndocumentName",
            "baseName": "sEzsigndocumentName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EzsigndocumentRequestCompound.attributeTypeMap;
    }
}

export namespace EzsigndocumentRequestCompound {
    export enum EEzsigndocumentSourceEnum {
        Base64 = <any> 'Base64'
    }
    export enum EEzsigndocumentFormatEnum {
        Pdf = <any> 'Pdf'
    }
}
