/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsignsignatureCreateObjectV1ResponseMPayload } from './ezsignsignatureCreateObjectV1ResponseMPayload';

export class EzsignsignatureCreateObjectV1ResponseAllOf {
    'mPayload': EzsignsignatureCreateObjectV1ResponseMPayload;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mPayload",
            "baseName": "mPayload",
            "type": "EzsignsignatureCreateObjectV1ResponseMPayload"
        }    ];

    static getAttributeTypeMap() {
        return EzsignsignatureCreateObjectV1ResponseAllOf.attributeTypeMap;
    }
}

