/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsignfoldersignerassociationRequest } from './ezsignfoldersignerassociationRequest';

export class EzsignfolderRequestCompoundAllOf {
    /**
    * An array of signers that will be invited to sign the Ezsigndocuments
    */
    'a_Ezsignfoldersignerassociation': Array<EzsignfoldersignerassociationRequest>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "a_Ezsignfoldersignerassociation",
            "baseName": "a_Ezsignfoldersignerassociation",
            "type": "Array<EzsignfoldersignerassociationRequest>"
        }    ];

    static getAttributeTypeMap() {
        return EzsignfolderRequestCompoundAllOf.attributeTypeMap;
    }
}

