/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A Ezsignsigner->Contact Object and children to create a complete structure
*/
export class EzsignsignerRequestCompoundContact {
    /**
    * The first name of the Contact
    */
    'sContactFirstname': string;
    /**
    * The last name of the Contact
    */
    'sContactLastname': string;
    /**
    * The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English|
    */
    'fkiLanguageID': number;
    /**
    * The email address of the contact. Must be filled if email authentification was requested
    */
    'sEmailAddress'?: string;
    /**
    * The Phone number of the contact. Use format \"5149901516\" for North American Numbers (Without \"1\" for long distance code) you would dial like this: 1-514-990-1516. Use format \"498945233886\" for international numbers (Without \"011\") you would dial like this: +49 89 452 33 88-6. In this example \"49\" is the country code of Germany.
    */
    'sPhoneNumber'?: string;
    /**
    * The Cell Phone number of the contact. Use format \"5149901516\" for North American Numbers (Without \"1\" for long distance code) you would dial like this: 1-514-990-1516. Use format \"498945233886\" for international numbers (Without \"011\") you would dial like this: +49 89 452 33 88-6. In this example \"49\" is the country code of Germany.
    */
    'sPhoneNumberCell'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sContactFirstname",
            "baseName": "sContactFirstname",
            "type": "string"
        },
        {
            "name": "sContactLastname",
            "baseName": "sContactLastname",
            "type": "string"
        },
        {
            "name": "fkiLanguageID",
            "baseName": "fkiLanguageID",
            "type": "number"
        },
        {
            "name": "sEmailAddress",
            "baseName": "sEmailAddress",
            "type": "string"
        },
        {
            "name": "sPhoneNumber",
            "baseName": "sPhoneNumber",
            "type": "string"
        },
        {
            "name": "sPhoneNumberCell",
            "baseName": "sPhoneNumberCell",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EzsignsignerRequestCompoundContact.attributeTypeMap;
    }
}

