/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An Ezsignpage Object
*/
export class EzsignpageResponse {
    /**
    * The unique ID of the Ezsignpage
    */
    'pkiEzsignpageID': number;
    /**
    * The Width of the page\'s image in pixels calculated at 100 DPI
    */
    'iEzsignpageWidthimage': number;
    /**
    * The Height of the page\'s image in pixels calculated at 100 DPI
    */
    'iEzsignpageHeightimage': number;
    /**
    * The Width of the page in points calculated at 72 DPI
    */
    'iEzsignpageWidthpdf': number;
    /**
    * The Height of the page in points calculated at 72 DPI
    */
    'iEzsignpageHeightpdf': number;
    /**
    * The page number in the Ezsigndocument
    */
    'iEzsignpagePagenumber': number;
    /**
    * The Url to the Ezsignpage\'s rasterized image.  Url will expire after 5 minutes.
    */
    'sImageUrl': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pkiEzsignpageID",
            "baseName": "pkiEzsignpageID",
            "type": "number"
        },
        {
            "name": "iEzsignpageWidthimage",
            "baseName": "iEzsignpageWidthimage",
            "type": "number"
        },
        {
            "name": "iEzsignpageHeightimage",
            "baseName": "iEzsignpageHeightimage",
            "type": "number"
        },
        {
            "name": "iEzsignpageWidthpdf",
            "baseName": "iEzsignpageWidthpdf",
            "type": "number"
        },
        {
            "name": "iEzsignpageHeightpdf",
            "baseName": "iEzsignpageHeightpdf",
            "type": "number"
        },
        {
            "name": "iEzsignpagePagenumber",
            "baseName": "iEzsignpagePagenumber",
            "type": "number"
        },
        {
            "name": "sImageUrl",
            "baseName": "sImageUrl",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EzsignpageResponse.attributeTypeMap;
    }
}

