/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Request for the /1/object/ezsigndocument/{pkiEzsigndocumentID}/applyezsigntemplate API Request
*/
export class EzsigndocumentApplyEzsigntemplateV1Request {
    /**
    * The unique ID of the Ezsigndocument
    */
    'fkiEzsigntemplateID': number;
    'a_sEzsigntemplatesigner': Array<string>;
    'a_pkiEzsignfoldersignerassociationID': Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fkiEzsigntemplateID",
            "baseName": "fkiEzsigntemplateID",
            "type": "number"
        },
        {
            "name": "a_sEzsigntemplatesigner",
            "baseName": "a_sEzsigntemplatesigner",
            "type": "Array<string>"
        },
        {
            "name": "a_pkiEzsignfoldersignerassociationID",
            "baseName": "a_pkiEzsignfoldersignerassociationID",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return EzsigndocumentApplyEzsigntemplateV1Request.attributeTypeMap;
    }
}

