/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsignsignatureRequest } from './ezsignsignatureRequest';

/**
* Request for the /1/object/ezsignsignature/editObject API Request
*/
export class EzsignsignatureEditObjectV1Request {
    'objEzsignsignature'?: EzsignsignatureRequest;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objEzsignsignature",
            "baseName": "objEzsignsignature",
            "type": "EzsignsignatureRequest"
        }    ];

    static getAttributeTypeMap() {
        return EzsignsignatureEditObjectV1Request.attributeTypeMap;
    }
}

