/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsignsignerRequestCompound } from './ezsignsignerRequestCompound';

export class EzsignfoldersignerassociationRequestCompoundAllOf {
    'objEzsignsigner'?: EzsignsignerRequestCompound;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objEzsignsigner",
            "baseName": "objEzsignsigner",
            "type": "EzsignsignerRequestCompound"
        }    ];

    static getAttributeTypeMap() {
        return EzsignfoldersignerassociationRequestCompoundAllOf.attributeTypeMap;
    }
}

