/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.31
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Frequency at which reminders will be sent to signers that haven\'t signed the documents
*/
export enum FieldEEzsignfolderSendreminderfrequency {
    None = <any> 'None',
    Daily = <any> 'Daily',
    Weekly = <any> 'Weekly'
}
