/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddressRequest } from './addressRequest';
import { ContactRequestCompound } from './contactRequestCompound';

export class FranchisereferalincomeRequestCompoundAllOf {
    'objAddress'?: AddressRequest;
    'a_objContact': Array<ContactRequestCompound>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objAddress",
            "baseName": "objAddress",
            "type": "AddressRequest"
        },
        {
            "name": "a_objContact",
            "baseName": "a_objContact",
            "type": "Array<ContactRequestCompound>"
        }    ];

    static getAttributeTypeMap() {
        return FranchisereferalincomeRequestCompoundAllOf.attributeTypeMap;
    }
}

