/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsignfolderRequest } from './ezsignfolderRequest';

/**
* Request for the /1/object/ezsignfolder/editObject API Request
*/
export class UNUSEDEzsignfolderEditObjectV1Request {
    'objEzsignfolder'?: EzsignfolderRequest;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objEzsignfolder",
            "baseName": "objEzsignfolder",
            "type": "EzsignfolderRequest"
        }    ];

    static getAttributeTypeMap() {
        return UNUSEDEzsignfolderEditObjectV1Request.attributeTypeMap;
    }
}

