/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.31
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EzsigndocumentRequest } from './ezsigndocumentRequest';

/**
* Request for the /1/object/ezsigndocument/editObject API Request
*/
export class UNUSEDEzsigndocumentEditObjectV1Request {
    'objEzsigndocument'?: EzsigndocumentRequest;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objEzsigndocument",
            "baseName": "objEzsigndocument",
            "type": "EzsigndocumentRequest"
        }    ];

    static getAttributeTypeMap() {
        return UNUSEDEzsigndocumentEditObjectV1Request.attributeTypeMap;
    }
}

