/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserCreateEzsignuserV1ResponseMPayload } from './userCreateEzsignuserV1ResponseMPayload';

export class UserCreateEzsignuserV1ResponseAllOf {
    'mPayload': UserCreateEzsignuserV1ResponseMPayload;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mPayload",
            "baseName": "mPayload",
            "type": "UserCreateEzsignuserV1ResponseMPayload"
        }    ];

    static getAttributeTypeMap() {
        return UserCreateEzsignuserV1ResponseAllOf.attributeTypeMap;
    }
}

