/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.  We provide SDKs for customers. They are generated using OpenAPI codegen, we encourage customers to use them as we also provide samples for them.  You can choose to build your own implementation manually or can use any compatible OpenAPI 3.0 generator like Swagger Codegen, OpenAPI codegen or any commercial generators.  If you need helping understanding how to use this API, don\'t waste too much time looking for it. Contact support-api@ezmax.ca, we\'re here to help. We are developpers so we know programmers don\'t like bad documentation. If you don\'t find what you need in the documentation, let us know, we\'ll improve it and put you rapidly up on track.
 *
 * The version of the OpenAPI document: 1.0.27
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Payload for the /1/module/user/createEzsignuser API Request
*/
export class UserCreateEzsignuserV1ResponseMPayload {
    /**
    * An array of email addresses that succeeded.
    */
    'a_sEmailAddressSuccess': Array<string>;
    /**
    * An array of email addresses that failed.
    */
    'a_sEmailAddressFailure': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "a_sEmailAddressSuccess",
            "baseName": "a_sEmailAddressSuccess",
            "type": "Array<string>"
        },
        {
            "name": "a_sEmailAddressFailure",
            "baseName": "a_sEmailAddressFailure",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return UserCreateEzsignuserV1ResponseMPayload.attributeTypeMap;
    }
}

