/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.  We provide SDKs for customers. They are generated using OpenAPI codegen, we encourage customers to use them as we also provide samples for them.  You can choose to build your own implementation manually or can use any compatible OpenAPI 3.0 generator like Swagger Codegen, OpenAPI codegen or any commercial generators.  If you need helping understanding how to use this API, don\'t waste too much time looking for it. Contact support-api@ezmax.ca, we\'re here to help. We are developpers so we know programmers don\'t like bad documentation. If you don\'t find what you need in the documentation, let us know, we\'ll improve it and put you rapidly up on track.
 *
 * The version of the OpenAPI document: 1.0.27
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A webhook object
*/
export class WebhookResponse {
    /**
    * The Webhook ID. This value is visible in the admin interface.
    */
    'pkiWebhookID': number;
    /**
    * The Module generating the Event.
    */
    'eWebhookModule': WebhookResponse.EWebhookModuleEnum;
    /**
    * This Ezsign Event. This property will be set only if the Module is \"Ezsign\".
    */
    'eWebhookEzsignevent'?: WebhookResponse.EWebhookEzsigneventEnum;
    /**
    * The Customer Code in which the event was generated
    */
    'pksCustomerCode': string;
    /**
    * The url being called
    */
    'sWebhookUrl': string;
    /**
    * The email that will receive the webhook in case all attempts fail.
    */
    'sWebhookEmailfailed': string;
    /**
    * This Management Event. This property will be set only if the Module is \"Management\".
    */
    'eWebhookManagementevent'?: WebhookResponse.EWebhookManagementeventEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pkiWebhookID",
            "baseName": "pkiWebhookID",
            "type": "number"
        },
        {
            "name": "eWebhookModule",
            "baseName": "eWebhookModule",
            "type": "WebhookResponse.EWebhookModuleEnum"
        },
        {
            "name": "eWebhookEzsignevent",
            "baseName": "eWebhookEzsignevent",
            "type": "WebhookResponse.EWebhookEzsigneventEnum"
        },
        {
            "name": "pksCustomerCode",
            "baseName": "pksCustomerCode",
            "type": "string"
        },
        {
            "name": "sWebhookUrl",
            "baseName": "sWebhookUrl",
            "type": "string"
        },
        {
            "name": "sWebhookEmailfailed",
            "baseName": "sWebhookEmailfailed",
            "type": "string"
        },
        {
            "name": "eWebhookManagementevent",
            "baseName": "eWebhookManagementevent",
            "type": "WebhookResponse.EWebhookManagementeventEnum"
        }    ];

    static getAttributeTypeMap() {
        return WebhookResponse.attributeTypeMap;
    }
}

export namespace WebhookResponse {
    export enum EWebhookModuleEnum {
        Ezsign = <any> 'Ezsign',
        Management = <any> 'Management'
    }
    export enum EWebhookEzsigneventEnum {
        DocumentCompleted = <any> 'DocumentCompleted',
        FolderCompleted = <any> 'FolderCompleted'
    }
    export enum EWebhookManagementeventEnum {
        UserCreated = <any> 'UserCreated'
    }
}
