/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.31
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A webhook object
*/
export class WebhookResponse {
    /**
    * The Webhook ID. This value is visible in the admin interface.
    */
    'pkiWebhookID': number;
    /**
    * The Module generating the Event.
    */
    'eWebhookModule': WebhookResponse.EWebhookModuleEnum;
    /**
    * This Ezsign Event. This property will be set only if the Module is \"Ezsign\".
    */
    'eWebhookEzsignevent'?: WebhookResponse.EWebhookEzsigneventEnum;
    /**
    * The Customer Code in which the event was generated
    */
    'pksCustomerCode': string;
    /**
    * The url being called
    */
    'sWebhookUrl': string;
    /**
    * The email that will receive the webhook in case all attempts fail.
    */
    'sWebhookEmailfailed': string;
    /**
    * This Management Event. This property will be set only if the Module is \"Management\".
    */
    'eWebhookManagementevent'?: WebhookResponse.EWebhookManagementeventEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pkiWebhookID",
            "baseName": "pkiWebhookID",
            "type": "number"
        },
        {
            "name": "eWebhookModule",
            "baseName": "eWebhookModule",
            "type": "WebhookResponse.EWebhookModuleEnum"
        },
        {
            "name": "eWebhookEzsignevent",
            "baseName": "eWebhookEzsignevent",
            "type": "WebhookResponse.EWebhookEzsigneventEnum"
        },
        {
            "name": "pksCustomerCode",
            "baseName": "pksCustomerCode",
            "type": "string"
        },
        {
            "name": "sWebhookUrl",
            "baseName": "sWebhookUrl",
            "type": "string"
        },
        {
            "name": "sWebhookEmailfailed",
            "baseName": "sWebhookEmailfailed",
            "type": "string"
        },
        {
            "name": "eWebhookManagementevent",
            "baseName": "eWebhookManagementevent",
            "type": "WebhookResponse.EWebhookManagementeventEnum"
        }    ];

    static getAttributeTypeMap() {
        return WebhookResponse.attributeTypeMap;
    }
}

export namespace WebhookResponse {
    export enum EWebhookModuleEnum {
        Ezsign = <any> 'Ezsign',
        Management = <any> 'Management'
    }
    export enum EWebhookEzsigneventEnum {
        DocumentCompleted = <any> 'DocumentCompleted',
        FolderCompleted = <any> 'FolderCompleted'
    }
    export enum EWebhookManagementeventEnum {
        UserCreated = <any> 'UserCreated'
    }
}
