/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A Word Position Object
*/
export class WordPositionResponse {
    /**
    * The page where the word occurence was found
    */
    'iPage'?: number;
    /**
    * The X coordinate (Horizontal) where the Word occurence was found.  Coordinate is calculated at 100dpi (dot per inch).
    */
    'iX'?: number;
    /**
    * The Y coordinate (Vertical) where the Word occurence was found.  Coordinate is calculated at 100dpi (dot per inch).
    */
    'iY'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "iPage",
            "baseName": "iPage",
            "type": "number"
        },
        {
            "name": "iX",
            "baseName": "iX",
            "type": "number"
        },
        {
            "name": "iY",
            "baseName": "iY",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return WordPositionResponse.attributeTypeMap;
    }
}

